### ISSUE TITLE
Cant´t install requirements (getopt)

### ISSUE THREAD

**Issue by NoSkillFound** [BeyYT/BeyDos#2]
First, i am a noob at coding and new to github so dont blame me if i do something wrong please xd.
**My issue is:**

When trying to do pip install -r requirements.txt (in this directory) it says:

"_ERROR: Could not find a version that satisfies the requirement getopt (from versions: none)
ERROR: No matching distribution found for getopt_"

Idk why this is happening, i have python and stuff installed and pip install -r requirements.txt works at other things.
Help would be great and have a nice day :)

**Comment by BeyYT** [comment]
Hey! I haven’t updated this DOS tool since a while.

most of these issues are module install related.

change Getopt to argparse in requirements.txt

This should help.
